Add custom domain support to Nest CLI
hackclub/nest pull request #28
Opened 2024-04-08 03:39 UTC by aboutdavid

2024-04-08 22:10 UTC, aboutdavid commented
Added FQDN validation + updated error message so it shows "None" instead of a blank CNAME record

2024-04-11 00:07 UTC, polypixeldev requested changes
Couple quick things, otherwise LGTM!

2024-04-11 00:07 UTC, polypixeldev commented on cli/add_domain.sh
> +	echo "You already have this subdomain ($DOMAIN)!"
```suggestion
	echo "You already have this custom domain ($DOMAIN)!"
```

2024-04-11 00:07 UTC, polypixeldev commented on cli/add_domain.sh
> +NEEDED_CNAME="$USER.hackclub.app"
```suggestion
NEEDED_CNAME="$USER.hackclub.app."
```
From my testing, the `dig` command will return the full DNS label with a trailing `.`

2024-04-11 00:12 UTC, polypixeldev approved these changes
LGTM!

2024-04-11 00:20 UTC, merged