Add `setup` command + `setup docker` subcommand to nest CLI
hackclub/nest pull request #34
Opened 2024-04-12 22:46 UTC by hello-smile6

This PR adds a `setup` command with a `docker` subcommand that configures rootless Docker to the nest CLI.

2024-04-12 23:49 UTC, polypixeldev requested changes
just a couple things!

2024-04-12 23:49 UTC, polypixeldev commented on cli/cli.rb
> +    desc "setup SUBCOMMAND ...ARGS", "set something up on your nest account"
```suggestion
    desc "setup SUBCOMMAND ...ARGS", "setup a tool to use on nest"
    subcommand "setup", Setup
```
I think this wording is better, and missing the subcommand

2024-04-13 00:11 UTC, polypixeldev approved these changes
LGTM!

2024-04-13 00:12 UTC, polypixeldev commented
if there's nothing else for this PR, can you un-draft it?

2024-04-13 01:30 UTC, hello-smile6 commented
This should be ready to merge if someone would be willing to

2024-04-14 16:02 UTC, merged